### ISSUE TITLE
throw new TypeError('Only absolute URLs are supported'); on account creation

### ISSUE THREAD

**Issue by trentnbauer** [NorthDevelopment/NorthClient#34]
Server logs:

```
  _   _            _   _      ____ _ _            _   
 | \ | | ___  _ __| |_| |__  / ___| (_) ___ _ __ | |_ 
 |  \| |/ _ \| '__| __| '_ \| |   | | |/ _ \ '_ \| __|
 | |\  | (_) | |  | |_| | | | |___| | |  __/ | | | |_ 
 |_| \_|\___/|_|   \__|_| |_|\____|_|_|\___|_| |_|\__|
                                                      
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Github] https://github.com/NorthDevelopment/NorthClient
[Discord] https://discord.gg/c2V7NKKWCT
[NorthClient] Copyright 2022-2023 ©️ NorthDevelopment
[NorthClient] All Rights Reserved.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[NorthClient] Loaded Dashboard on the port 9000
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[NorthClient] './routes' loaded         ✅
[NorthClient] './handlers' loaded       ✅
[NorthClient] './themes' loaded         ✅
[NorthClient] './settings.yml' loaded   ✅
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[NorthClient] File './db.sqlite' backed up to './dbbackup/sqlite/backup_db_2023-11-4_23-6-54.sqlite' ✅
[NorthClient] File './sessions.db' backed up to './dbbackup/session/backup_sessions_2023-11-4_23-6-54.db' ✅
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[NorthClient] The dbbackup folder was successfully created!
[NorthClient] The session folder was successfully created!
[NorthClient] The sqlite folder was successfully created!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
/home/container/node_modules/node-fetch/lib/index.js:1327
                throw new TypeError('Only absolute URLs are supported');
        ^
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/container/node_modules/node-fetch/lib/index.js:1327:9)
    at /home/container/node_modules/node-fetch/lib/index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (/home/container/node_modules/node-fetch/lib/index.js:1437:9)
    at /home/container/routes/auth/email.js:37:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This occurs when trying to create an manual account or using Oauth via Discord.
New install.

Using a subdomain, https://northclient.mydomain.com via a Cloudflare tunnel.

**Comment by trentnbauer** [comment]
Is this project dead?

**Comment by jojobingsa** [comment]
Please have a look at our Discord in #Accnouncement where you can find everything you need to know.
